extern class Error

func foo(bar) ~ Error {
}

try {
	foo(42)
}