extern BadError

func foo(bar) ~ BadError {
}